version: '3.8'

services: 
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: yeah
      MARIADB_DATABASE: ${DB_NAME}
    networks:
      - docker-service
  
  app:
    depends_on:
      - mariadb
    build: ./
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports: 
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - docker-service

networks:
  docker-service:

volumes:
  db:
